Update commands in user guide
AY2223S1-CS2103T-W09-3/tp pull request #154
Opened 2022-10-18 16:14 UTC by richavm14

2022-10-18 16:31 UTC, TJun-Jie requested changes

2022-10-18 16:31 UTC, TJun-Jie commented on docs/UserGuide.md
> +| **Member Delete**   | `delete p/GLOBAL-PERSON-INDEX` <br> e.g. `delete n/1`                                                                                                       |
Example wrong , should be p instead of n

2022-10-18 16:31 UTC, TJun-Jie commented on docs/UserGuide.md
> +| **Task Delete**     | `taskdelete t/TEAM-INDEX task/TASK-INDEX` <br> e.g. `taskdelete t/Create GUI for the Duke app`                                                              |
Example wrong

2022-10-18 16:31 UTC, TJun-Jie commented on docs/UserGuide.md
> +| **Task Mark**       | `taskmark t/TEAM-INDEX task/TASK-INDEX` <br> e.g. `taskmark t/1 t/1`                                                                                        |
Example format wrong

2022-10-18 16:31 UTC, TJun-Jie commented on docs/UserGuide.md
> +| **Task Mark**       | `taskmark t/TEAM-INDEX task/TASK-INDEX` <br> e.g. `taskmark t/1 t/1`                                                                                        |
Example format wrong

2022-10-18 16:31 UTC, TJun-Jie commented on docs/UserGuide.md
> +| **Task unMark**     | `taskunmark t/TEAM-INDEX task/TASK-INDEX` <br> e.g. `taskunmark t/1 t/1`                                                                                    |
Example format wrong

2022-10-19 07:18 UTC, richavm14 commented on docs/UserGuide.md
> +| **Member Delete**   | `delete p/GLOBAL-PERSON-INDEX` <br> e.g. `delete n/1`                                                                                                       |
Have updated in recent commit!

2022-10-19 07:18 UTC, richavm14 commented on docs/UserGuide.md
> +| **Task Delete**     | `taskdelete t/TEAM-INDEX task/TASK-INDEX` <br> e.g. `taskdelete t/Create GUI for the Duke app`                                                              |
Have updated in recent commit!

2022-10-19 07:19 UTC, richavm14 commented on docs/UserGuide.md
> +| **Task Mark**       | `taskmark t/TEAM-INDEX task/TASK-INDEX` <br> e.g. `taskmark t/1 t/1`                                                                                        |
Have updated in recent commit!

2022-10-19 07:19 UTC, richavm14 commented on docs/UserGuide.md
> +| **Task Mark**       | `taskmark t/TEAM-INDEX task/TASK-INDEX` <br> e.g. `taskmark t/1 t/1`                                                                                        |
Have updated in recent commit!

2022-10-19 07:19 UTC, richavm14 commented on docs/UserGuide.md
> +| **Task unMark**     | `taskunmark t/TEAM-INDEX task/TASK-INDEX` <br> e.g. `taskunmark t/1 t/1`                                                                                    |
Have updated in recent commit!

2022-10-20 01:55 UTC, merged