Update command format and description in User guide
AY2223S1-CS2103T-W09-3/tp pull request #181
Opened 2022-10-26 08:29 UTC by richavm14

2022-10-26 13:37 UTC, JonathanWiguna requested changes

2022-10-26 13:37 UTC, JonathanWiguna commented on docs/UserGuide.md
> +* `unassign m/1 t/1` removes first member from first team.
I think instead of 'removes first member', 'removes the person with global index 1', since the member-index refers to their index in the global index.

2022-10-26 13:37 UTC, JonathanWiguna commented on docs/UserGuide.md
> +Format: `taskadd t/TEAM-INDEX n/TASK-NAME [d/YYYY-MM-DD]`
```suggestion
Format: `taskadd t/TEAM-INDEX n/TASK-NAME [d/DD-MM-YYYY]`
```
Sorry last time I gave the wrong format, this is the valid one

2022-10-26 13:37 UTC, JonathanWiguna commented on docs/UserGuide.md
> +* `taskadd t/1 n/Finish project d/2023-12-24` Adds a new task to team with index 1 with the description
```suggestion
* `taskadd t/1 n/Finish project d/24-12-2023` Adds a new task to team with index 1 with the description 
```

2022-10-26 13:37 UTC, JonathanWiguna commented on docs/UserGuide.md
> +UnMarks a task as pending.
Should it be that, or 'Marks a task as pending'?

2022-10-26 13:37 UTC, JonathanWiguna commented on docs/UserGuide.md
> +* `createteam n/Team1` Adds a team with the name Team1.
I think currently the format to create team is just `create`

2022-10-26 13:37 UTC, JonathanWiguna commented on docs/UserGuide.md
> +Format: `deleteteam t/TEAM-INDEX`
```suggestion
Format: `delteam t/TEAM-INDEX`
```

2022-10-26 13:37 UTC, JonathanWiguna commented on docs/UserGuide.md
> +* `deleteteam t/1` Deletes the first team.
```suggestion
* `delteam t/1` Deletes the first team.
```

2022-10-26 13:37 UTC, JonathanWiguna commented on docs/UserGuide.md
> +| **Team Delete**     | `delteam t/TEAM-INDEX` <br> e.g. `deleteteam t/1`                                                                                                              |
```suggestion
| **Team Delete**     | `delteam t/TEAM-INDEX` <br> e.g. `delteam t/1`                                                                                                              |
```

2022-10-26 13:37 UTC, JonathanWiguna commented on docs/UserGuide.md
> +| **Team Add**        | `createteam n/TEAM-NAME` <br> e.g. `createteam n/TEAM1`                                                                                                        |
```suggestion
| **Team Add**        | `create n/TEAM-NAME` <br> e.g. `create n/TEAM1`                                                                                                        |
```

2022-10-26 13:37 UTC, JonathanWiguna commented on docs/UserGuide.md
> +| **Task Add**        | `taskadd t/TEAM-INDEX n/TASK-NAME [d/YYYY-MM-DD]` <br> e.g. `taskadd t/1 n/Finish project d/2023-12-24`                                                        |
```suggestion
| **Task Add**        | `taskadd t/TEAM-INDEX n/TASK-NAME [d/DD-MM-YYYY]` <br> e.g. `taskadd t/1 n/Finish project d/24-12-2023`                                                        |
```

2022-10-26 15:21 UTC, richavm14 commented on docs/UserGuide.md
> +* `unassign m/1 t/1` removes first member from first team.
Have updated in recent commit!

2022-10-26 15:21 UTC, richavm14 commented on docs/UserGuide.md
> +Format: `taskadd t/TEAM-INDEX n/TASK-NAME [d/YYYY-MM-DD]`
Have updated in recent commit!

2022-10-26 15:21 UTC, richavm14 commented on docs/UserGuide.md
> +* `taskadd t/1 n/Finish project d/2023-12-24` Adds a new task to team with index 1 with the description
Have updated in recent commit!

2022-10-26 15:21 UTC, richavm14 commented on docs/UserGuide.md
> +* `createteam n/Team1` Adds a team with the name Team1.
Have updated in recent commit!

2022-10-26 15:22 UTC, richavm14 commented on docs/UserGuide.md
> +Format: `deleteteam t/TEAM-INDEX`
Have updated in recent commit!

2022-10-26 15:22 UTC, richavm14 commented on docs/UserGuide.md
> +* `deleteteam t/1` Deletes the first team.
Have updated in recent commit!

2022-10-26 15:22 UTC, richavm14 commented on docs/UserGuide.md
> +| **Team Delete**     | `delteam t/TEAM-INDEX` <br> e.g. `deleteteam t/1`                                                                                                              |
Have updated in recent commit!

2022-10-26 15:22 UTC, richavm14 commented on docs/UserGuide.md
> +| **Task Add**        | `taskadd t/TEAM-INDEX n/TASK-NAME [d/YYYY-MM-DD]` <br> e.g. `taskadd t/1 n/Finish project d/2023-12-24`                                                        |
Have updated in recent commit!

2022-10-27 00:03 UTC, JonathanWiguna approved these changes

2022-10-27 00:03 UTC, merged